//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5Pr
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPh
    {
        public int ID_rph { get; set; }
        public Nullable<int> ID_photog { get; set; }
        public Nullable<int> ID_loc { get; set; }
        public Nullable<int> ID_client { get; set; }
        public string Loc { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Location Location { get; set; }
        public virtual Photographer Photographer { get; set; }
    }
}
